@startuml
title seamingのクラス図

class ビューマネージャ << control >> {
    + 見えている部分のノード : ノード[]
    + ノード間をつなぐリンク : リンク[]
    + 表示範囲 : int[]
    + 表示範囲を変更する (int[]) : void
    + リンクを作成する (void) : void
    + ノードの可視化 (void) : void
    + 詳細情報を表示 (void) : void
    + 子ノードを取得\n(ノードのID : String) : ノードのID (String)
}

class ノードマネージャ << control >> {
    + ユーザのノード : ノード[]
    + ユーザIDの取得\n(セッション鍵 : String) : String
}

class 非可変情報 << entity >> {
    + ノードのID : String
    + ノードの名前 : String
    + ノードの説明: String
    + 教材サイトのURL : String
    + ノードの座標 : int[]
    + 親ノード : ノード
    + 子ノードのリスト : ノード[]
    + ノードの習熟度 : int = Null
    + 親ノードを追加 : (ノードのID : String) : void
    + 親ノードを削除 : (ノードのID : String) : void
    + 子ノードを追加 : (ノードのID : String) : void
    + 子ノードを削除 : (ノードのID : String) : void
}

class 可変情報 << entity >> {
    + セッション鍵 : String
    + ユーザのID : String
    + ノードのID : String
    + ノードの習熟度 : int 

    + 習熟度を返す\n(セッション鍵 : String, ノードのID : String) : int
    + 習熟度を変更\n(セッション鍵 : String, ノードのID : String) : int
}

class ノード << control >> {
    + ノードのID：String
}


class ユーザ << entity >> {
    + ユーザのID : String
    + ユーザのパスワード : String
    + セッション鍵 : String
}

class ユーザマネージャ << control >> {
    + ユーザのID : String
    + ユーザのパスワード : String
    + ユーザ登録\n(ユーザID : String, パスワード : String) : void
    + ログイン（セッション鍵の発行）\n(ユーザID : String, パスワード : String) : String
    + ユーザIDの取得\n(セッション鍵 : String) : String
}

Note bottom of ユーザマネージャ : ログイン処理と\nユーザID・セッション鍵の結びつけを担当する

Note top of ビューマネージャ : ノードの可視化と、\nノードへのイベント通知を担当する

Note left of ノードマネージャ : セッション中のユーザの\nノード情報の管理を担当する

ユーザ -down- ビューマネージャ
ユーザ -down- ユーザマネージャ
ビューマネージャ -- ノードマネージャ
ノードマネージャ -right- ユーザマネージャ
ノードマネージャ --* ノード
非可変情報 -up-|> ノード
可変情報 -up-|> ノード
@enduml