@startuml

title seamingのシーケンス図\n・未登録者の操作


actor 未登録者 

未登録者 -> ノードマップ : マップをドラッグ
ノードマップ -> 表示マネージャ : 表示位置の変更
表示マネージャ -> ノード : ノード座標の取得
表示マネージャ <-- ノード : ノード座標を返す
ノードマップ <-- 表示マネージャ : 可視ノードの位置を返す
未登録者 <-- ノードマップ : マップを表示する

|||

未登録者 -> ノード : ノードをクリック
未登録者 <-- ノード : ノードの詳細情報ポップアップを表示

@enduml