@startuml

title seamingのシーケンス図\n・未登録者の操作


actor 未登録者 

未登録者 -> ノードマップ : 表示位置の変更
ノードマップ -> ノード : ノード座標の取得
ノードマップ <-- ノード : ノード座標を返す
未登録者 <-- ノードマップ : 可視ノードを表示する

|||

未登録者 -> ノード : ノードをクリック
未登録者 <-- ノード : ノードの詳細情報ポップアップを表示

@enduml