@startuml

title seamingのシーケンス図\n・管理者の操作


actor 管理者 

participant 管理者 order 10
participant ノードマップ order 20
participant 表示マネージャ order 30
participant ノード一覧 order 35
participant ノード order 40
participant ユーザマネージャ order 50

管理者 -> ユーザマネージャ : ユーザ登録
ユーザマネージャ -> ユーザマネージャ : 管理者としてログイン
管理者 -> ユーザマネージャ : 管理者としてログイン
|||
管理者 -> ノード一覧 : ノードの検索
ノード一覧 -> ノード : ノードの情報の取得
|||
管理者 -> ノード : 教材サイトの変更
管理者 -> ノード : 位置の変更
|||
管理者 -> ノード一覧 : ノードの追加
ノード一覧 -> ノード : ノードの作成
ノード -> ノード : （新しい親ノード）\n加わった子ノードを追加
ノード -> ノード : （新しい子ノード）\n加わった親ノードを追加する変更
|||
管理者 -> ノード : （子ノード）\n親ノードの変更
ノード -> ノード : （古い親ノード）\nいなくなった子ノードを削除
ノード -> ノード : （新しい親ノード）\n加わった子ノードを追加
|||
管理者 -> ノード : （親ノード）\n子ノードの削除
ノード -> ノード : （削除された子ノード）\n親ノードの削除


@enduml