@startuml

title seamingのユースケース


actor 管理者
actor 学習者
actor 未登録者

usecase (ノードマップを見る)
usecase (管理者としてログイン) as 管理者ログイン
usecase (学習者としてログイン) as ログイン
usecase (ノードの配置を変える)
usecase (ノードの配置を保存する)
usecase (ユーザ登録をする)
usecase (教材サイトを登録する)
usecase (ノードの詳細を見る)
usecase (教材ページに移動する)
usecase (ノードの習熟度を見る)
usecase (ノードの作成をする)
usecase (ノードの削除をする)
usecase (ノードの親子関係を変更する)
usecase (ノードの習熟度を登録する)


ノードの習熟度を見る ..> ログイン
ノードの習熟度を登録する ..> ログイン


教材サイトを登録する ..> 管理者ログイン
ノードの作成をする ..> 管理者ログイン
ノードの親子関係を変更する ..> 管理者ログイン
ノードの削除をする ..> 管理者ログイン
ノードの配置を変える ..> 管理者ログイン
ノードの配置を保存する ..> 管理者ログイン

ノードの習熟度を見る .up.> ノードの詳細を見る
ノードの習熟度を登録する .up.> ノードの詳細を見る
教材ページに移動する .down.> ノードの詳細を見る
教材サイトを登録する .left.> ノードの詳細を見る

ノードの配置を変える .left.> ノードマップを見る


未登録者 <|-- 学習者


未登録者 --> ノードマップを見る
未登録者 --> ノードの詳細を見る
未登録者 -right-> 教材ページに移動する


学習者 --> ユーザ登録をする
学習者 --> ノードの習熟度を見る
学習者 --> ノードの習熟度を登録する


管理者 --> 教材サイトを登録する
管理者 --> ノードの作成をする
管理者 --> ノードの削除をする
管理者 --> ノードの親子関係を変更する
管理者 --> ノードの配置を変える
管理者 --> ノードの配置を保存する

@enduml